services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: Table
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - "5050:80"

  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql_container
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarefas
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: user
    ports:
      - "8080:80"
    depends_on:
      - mysql